jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t your-image-name:latest .

      - name: Log in to Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image to Registry
        run: docker push your-image-name:latest

      - name: Deploy to Production
        run: |
          # Add your deployment script or commands here
          echo "Deploying to production..."
